### ISSUE TITLE
Add `Apps` command

### ISSUE THREAD

**Issue by q231950** [xing/crep#62] opened 2018-02-02 17:18 UTC
In the past we found that sometimes it is cumbersome to find the right app to create a crash report for.

**Crep** should have a way to show a list of apps matching a version or parts of a version.

**Comment by BasThomas** [comment] 2018-02-02 17:19
Duplicate of #25?

**Comment by q231950** [comment] 2018-02-02 17:55
A little, @BasThomas . This one is about reporting an informational list of apps as a first step towards apps and apps with the same version

**Closed** 2018-02-26 18:45 UTC
